---
title: "Compare Temperature and Precipitation"
author: "Katie Renwick"
date: "6/30/2017"
output: beamer_presentation
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, message=F, warning=F, include=F)
```

```{r}
rm(list=ls())
library(tidyverse); theme_set(theme_bw(base_size=12)) # sized for ppt
library(rgdal)
library(raster)
library(zoo) #fucking hate time series!

# paths to data and folder for figures
dpath <- "/Users/poulterlab1/Documents/SageParm/data/"
fpath <- "/Users/poulterlab1/Documents/SageParm/figures/"
cpath <- "/Users/poulterlab1/Documents/SageParm/Daymet3_ID/" # climate data
mpath <- "/Users/poulterlab1/Documents/SageParm/data/ReynoldsC/MODIS/" # MERRA2 data

# color scheme
ggcolor <- c("#80cdc1","#018571", "#a6611a","#dfc27d")

############ Get station data and put in propper format
# Get station data for 2014- sent via email by Gerald Flerchinger, ARS
RC176 <- read.csv(paste(dpath, "ReynoldsC/176.wea.30min.2015.csv", sep="")) %>%
  mutate(Source="Station", Site="mbsec")
RC098c <- read.csv(paste(dpath, "ReynoldsC/098c.wea.30min.2015.csv", sep="")) %>%
  mutate(Source="Station", Site="wbsec")
RC127 <- read.csv(paste(dpath, "ReynoldsC/127.wea.30min.2015.csv", sep="")) %>%
  mutate(Source="Station", Site="losec")
RC138j10 <- read.csv(paste(dpath, "ReynoldsC/138j10.wea.30min.2015.csv", sep="")) %>%
  mutate(Source="Station", Site="h08ec")
RCweather <- rbind(RC176,RC098c,RC127,RC138j10)

# coordinates of flux sites:
sites <- read.csv(paste(dpath, "ReynoldsC/EC-CoreSites-coords.csv", sep=""))
ll <- dplyr::select(sites, Lon,Lat)
Site <- dplyr::select(sites, Site)

# Convert 30-min temp and precip to monthly 
RC2 <- RCweather %>% mutate(date=as.Date(datetimec)) %>%
  group_by(date,Source,Site) %>% # group by day to calculate days with precip
  summarise(dayppt=sum(ppta), daytemp=mean(tmp3), daysol=mean(sol)) %>%
  mutate(yearmon=format(date, format="%y-%m")) %>%
  group_by(yearmon,Source,Site) %>%
  summarise(temp=mean(daytemp), ppt=sum(dayppt), meansol=mean(daysol),
            wet=sum(dayppt>0))

head(RC2)

# Pull in daymet3 data, extract values for points
#Loop through the months and sample the climate data
nmonths <- 24
ClimateD3 <- NULL
TS <- unique(RC2$yearmon)

for(m in 1:nmonths){
  print(paste(round((m/nmonths)*100,2),"% finished"))
  #Sample tmean
  tmean.month.m <- raster(paste(cpath, "tmean_1980-2016.nc4", sep=""), 
                          band=(m+408), varname="tmean")    
  temp <- raster::extract(tmean.month.m, ll)
  ppt.month.m <- raster(paste(cpath, "prcp_1980-2016.nc4", sep=""), 
                        band=(m+408), varname="prcp")    
  ppt <- raster::extract(ppt.month.m, ll)
  
  # Get dates
  yearmon <- rep(TS[m], 4)
  all <- cbind(yearmon,Site,temp,ppt)
  ClimateD3 <- rbind(ClimateD3,all)
} 
ClimateD3 <- as_tibble(ClimateD3)
ClimateD32 <- ClimateD3 %>%
  mutate(Source="Daymet") %>%
  dplyr::select(yearmon, Source, Site, temp:ppt) %>%
  mutate(yearmon=as.character(yearmon))
head(ClimateD32)

# Pull in MERRA2 data, extract values for points
#Loop through the months and sample the climate data
nmonths <- 24
merD3 <- NULL

for(m in 1:nmonths){
  print(paste(round((m/nmonths)*100,2),"% finished"))
  #Sample tmean
  tmean.month.mm <- raster(paste(mpath, "tair-monthly.nc", sep=""), 
                          band=(m+408), varname="t2m")    
  temp <- raster::extract(tmean.month.mm, ll)
  ppt.month.m <- raster(paste(mpath, "prec-monthly.nc", sep=""), 
                        band=(m+408), varname="tp")    
  ppt <- raster::extract(ppt.month.m, ll)
  
  # Get dates
  yearmon <- rep(TS[m], 4)
  all <- cbind(yearmon,Site,temp,ppt)
  merD3 <- rbind(merD3,all)
} 
merD3 <- as_tibble(merD3)
merD32 <- merD3 %>%
  mutate(Source="MERRA2") %>%
  dplyr::select(yearmon, Source, Site, temp:ppt) %>%
  mutate(yearmon=as.character(yearmon))
head(merD32)

head(RC2)
all <- rbind.data.frame(RC2[,1:5], ClimateD32,merD32)
all$Source <- as.factor(all$Source)
all$Site <- as.factor(all$Site)
all$Date <- as.Date(as.yearmon(all$yearmon,format="%y-%m"))
head(all)
```

# Temperature

```{r, include=T}
###############################################################################

# Plot tmean
ggplot(data=all, aes(x=Date,y=temp, color=Source)) +
  geom_point(size=1) +
  geom_line(size=1) +
  ylab(expression("Temperature ("*~degree*"C)")) +
  xlab("Date (year-month)") +
  theme(axis.text.x = element_text(angle = 90, hjust = 1)) +
  facet_wrap(~Site)
```

# Precipitation

```{r, include=T}

## Precipitation
ggplot(data=all, aes(x=Date,y=ppt, color=Source)) +
  geom_point(size=1) +
  geom_line(size=1) +
  ylab("Precipitation (mm/month)") +
  xlab("Date (year-month)") +
  theme(axis.text.x = element_text(angle = 90, hjust = 1)) +
  facet_wrap(~Site)
```

# 2-year means

```{r, include=T}

# Mean over 2 years for each variable
all2 <- gather(all, Variable, value, temp:ppt)
ggplot(data=all2, aes(x=Site, y=value, color=Source)) +
  geom_boxplot(notch=T, size=1) +
  scale_color_manual(values=ggcolor, name="Data Source") +
  ylab("Value") +
  theme(axis.text.x = element_text(angle = 90, hjust = 1)) +
  facet_wrap(~Variable, scale="free")
```

# Location of sites in daymet grid

```{r, include=T}
# Plot sites over Daymet temperature
#convert the raster to points for plotting
map.p <- rasterToPoints(tmean.month.m)
df <- data.frame(map.p) %>%
  filter(x<=-116.7,x>=-116.77, y>=43.05,y<=43.18)
colnames(df) <- c("Longitude", "Latitude", "MAT")

# Plot Daymet grid with study sites shown
ggplot(data=df, aes(y=Latitude, x=Longitude)) +
  geom_raster(aes(fill=MAT)) +
  geom_point(data=sites, aes(x=Lon, y=Lat), color="white", size=2, shape=1) +
  geom_text(data=sites,aes(x=Lon, y=Lat,label=Site),nudge_y = .005, color="white") +
  theme_bw() +
  coord_equal() +
  scale_fill_gradient("Dec. 2015 Temp.") +
  theme(axis.title.x = element_text(size=16),
        axis.title.y = element_text(size=16, angle=90),
        axis.text.x = element_text(size=14),
        axis.text.y = element_text(size=14),
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        legend.position = "right",
        legend.key = element_blank())
```

# Location of sites in MERRA2 grid

```{r, include=T}
# Plot sites over MERRA temperature
#convert the raster to points for plotting
map.p <- rasterToPoints(tmean.month.mm)
df <- data.frame(map.p)
colnames(df) <- c("Longitude", "Latitude", "MAT")

# Plot MERRA grid with study sites shown
ggplot(data=df, aes(y=Latitude, x=Longitude)) +
  geom_raster(aes(fill=MAT)) +
  geom_point(data=sites, aes(x=Lon, y=Lat), color="white", size=2, shape=1) +
  geom_text(data=sites,aes(x=Lon, y=Lat,label=Site),nudge_y = .005, color="white") +
  theme_bw() +
  coord_equal() +
  scale_fill_gradient("Dec. 2015 Temp.") +
  theme(axis.title.x = element_text(size=16),
        axis.title.y = element_text(size=16, angle=90),
        axis.text.x = element_text(size=14),
        axis.text.y = element_text(size=14),
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        legend.position = "right",
        legend.key = element_blank())
```